langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- yes | gem update --system --force
- gem install bundler
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: n9Vl1fmkX2zK/6hOWdIsS7W0VuUYOQlRpwglOXtchcMBPgHwHbjQE0b7O3r3q+mbpvxsRMxv0ebj77Pp0D65Ty4U6AjKf0NlhbLK4JidnFt25Xq3df51FpfUegMVzS7aEXIzLr/RJvSFZMULVnaki8N5a0WL56mSoDkdKJFd452UasKaYPqr3/9fzi+aXUtbOonlew686pDC1CBrgu4ktZsYwvkR7e0kP4eZZioaVv+tumKFwMYrcruxQ5chuvYeVPNZTVBtRBOMEV6S+HGuqfJ1VF/2ByMwgZ4M3cS4+CxVUAhBIe7GXm9timqZlR67L00UAFWfQ2B2aRneLXMJMeuMLiuJNpetAVVWz2Vv28afklIsdYsScglcHiqLmfOziBIwWdRDU2gNnzlBVTHmnpXX7wn28KtI016Xyis7l3s5NOF0xua9wI8fszF7Zyc5U4nHfsNuQh+8150YWj6Tbx02GZp2eWQnXTPjXfHUsf0FfzoZXxbrZS+2P5ag29U9jYYf9Wa9AY4ICVets39xBfYp1ywisKs8QejF3+fYMWs346kIEe+1STwHWEcj2Sg1VdOB0z+YaZVo1qfG02ZZcafpZw3uTplLbFO+DDmMkP+Jdy0hKVFNkCPbKTFLZ2VemCUgB0B6p7nzzb7iJqptu6RnyEsWm5gc+F99r66yWHQ=
  app: km-sweater-weather-api
