# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 439cb15d905b80ef309d446eb2d62a3780cc79b3e12c67c22c8334374050624f44cbbbbe330937c29eba8d244a6a5dc32b04f98bc7ae5b16d0c88f478a2d8936

test:
  secret_key_base: 0ed149ef6f90ca6e907bc504c2cb65ffea655e07be3e5a938d5930371a4f35a9808c8921792aaa5abe8b8b81711f4bf96ecc0548b508998e792ee4f877258ef2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
